# Generated by Django 4.2.11 on 2024-03-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcards',
            new_name='Flashcard',
        ),
    ]
