# Generated by Django 4.2.11 on 2024-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_rename_flashcards_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
