# Generated by Django 4.2.11 on 2024-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_resource_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='filepath',
            field=models.FileField(default=None, upload_to='files/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
