# Generated by Django 4.2.11 on 2024-03-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_remove_resource_user_id_alter_flashcard_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='resource_id',
            new_name='resource',
        ),
    ]
