# Generated by Django 4.2.11 on 2024-03-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0005_rename_resource_id_flashcard_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='filename',
        ),
    ]
