# Generated by Django 4.2.11 on 2024-03-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0007_resource_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='user',
            new_name='user_id',
        ),
    ]
