# Generated by Django 4.2.11 on 2024-03-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0008_rename_user_resource_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='user_id',
            new_name='user',
        ),
    ]
